meta_product_name: "WhosIn"
meta_title: "WhosIn - Never miss a dinner with your friends"
meta_description: "You are annoyed by all the text conversations when you schedule a dinner? Join WhosIn and quickly set up your dinner with your friends. Make a list of what you need and what you cook and let us take care of the rest!"
meta_image: "logo.png"                       # should exist in `app/assets/images/`
